library(dplyr)
library(sparklyr)
library(shiny)
library(ggplot2)
library(plotly)
library(pysparklyr)
library(shinyjs)
library(tidyr)
library(dbplyr)
library(yaml)


.libPaths("C://Users//Gebruiker//Documents//.virtualenvs//r-sparklyr-databricks-13.3//Lib")
sc <- spark_connect(method = "databricks_connect", Sys.getenv("DATABRICKS_HOST"))
Sys.setenv(TZ = "Europe/Amsterdam")
